# Generated by Django 2.1.5 on 2019-03-07 13:45

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('forum', '0003_post_thread'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['pk']},
        ),
        migrations.AddField(
            model_name='post',
            name='options',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='post',
            name='tags_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=10), default=list,
                                                            size=None),
        ),
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments',
                                    to='forum.Post'),
        ),
        migrations.AlterField(
            model_name='post',
            name='thread',
            field=models.ForeignKey(help_text='Some usefull help text', null=True,
                                    on_delete=django.db.models.deletion.CASCADE, to='forum.Thread'),
        ),
    ]
