# Generated by Django 2.1.5 on 2019-01-22 13:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('blog', '0002_auto_20190117_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theme',
            name='image',
            field=models.ImageField(upload_to='uploads/'),
        ),
    ]
