# Generated by Django 2.1.5 on 2019-01-22 13:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=16, validators=[django.core.validators.MaxLengthValidator(16),
                                                                         django.core.validators.MinLengthValidator(
                                                                             3)])),
                ('join_date', models.DateField(auto_now_add=True)),
                ('username', models.CharField(max_length=16, validators=[django.core.validators.MaxLengthValidator(16),
                                                                         django.core.validators.MinLengthValidator(
                                                                             8)])),
                ('is_active', models.BooleanField(default=False)),
                ('company', models.CharField(blank=True, max_length=256, null=True)),
            ],
        ),
    ]
