# Generated by Django 2.1.5 on 2019-01-22 14:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('testuser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testuser',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='testuser',
            name='username',
            field=models.CharField(max_length=16, validators=[django.core.validators.MaxLengthValidator(16),
                                                              django.core.validators.MinLengthValidator(6)]),
        ),
    ]
