# Generated by Django 2.1.5 on 2019-02-02 14:14

from django.db import migrations, models

import testuser.models


class Migration(migrations.Migration):
    dependencies = [
        ('testuser', '0003_auto_20190124_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testuser',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=testuser.models.upload_to),
        ),
    ]
